"""Build a validation-first comparison of existing Sina embedding families.

The primary set uses every completed four-fold plain mean-pooled report that
is aligned to the same 4,928-row panel: four CNINFO-method transformer
families and four single-stock dense families. The source pipeline remains an
explicit column, so a model family represented by two pipelines is not
silently conflated. No embedding is generated by this script and test metrics
are never used to select a winner.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any, Iterable


EXPECTED_TEST_YEARS = (2023, 2024, 2025, 2026)
PRIMARY_CNINFO_MODELS = ("roberta", "bge_m3", "ckip_bert", "xlm_roberta_large")
PRIMARY_DENSE_MODELS = (
    "word2vec",
    "qwen3_embedding_8b",
    "bge_m3",
    "chinese_roberta",
)
MODEL_LABELS = {
    "roberta": "Chinese RoBERTa",
    "bge_m3": "BGE-M3",
    "ckip_bert": "Chinese BERT (CKIP)",
    "xlm_roberta_large": "XLM-R large",
    "word2vec": "Word2Vec",
    "qwen3_embedding_8b": "Qwen3 Embedding 8B",
    "chinese_roberta": "Chinese RoBERTa",
}


def _as_float(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _mean(values: Iterable[Any]) -> float | None:
    finite = [number for value in values if (number := _as_float(value)) is not None]
    return sum(finite) / len(finite) if finite else None


def _std(values: Iterable[Any]) -> float | None:
    finite = [number for value in values if (number := _as_float(value)) is not None]
    if not finite:
        return None
    mean = sum(finite) / len(finite)
    return (sum((value - mean) ** 2 for value in finite) / len(finite)) ** 0.5


def _targets(design: dict[str, Any]) -> tuple[str | None, str | None]:
    train = design.get("train_target", design.get("train_target_column"))
    evaluation = design.get("evaluation_target", design.get("evaluation_target_column"))
    return train, evaluation


def summarize_report_payload(
    payload: dict[str, Any],
    report_path: Path,
    *,
    source: str,
    comparison_set: str,
) -> dict[str, Any]:
    """Normalize one completed report into one comparison-table row."""
    design = payload.get("design", {})
    experiment = payload.get("experiment", {})
    results = payload.get("results", [])
    if not results:
        raise ValueError(f"report has no rolling results: {report_path}")
    train_target, evaluation_target = _targets(design)

    model = experiment.get("model", experiment.get("embedding_model"))
    if not model:
        raise ValueError(f"report has no embedding model: {report_path}")
    variant = experiment.get("variant", "plain")
    feature = experiment.get("feature", "global_mean")
    reducer = experiment.get("reducer", "none")
    validation_metrics = [row.get("validation_metrics", {}) for row in results]
    test_years = sorted(int(row["test_year"]) for row in results)
    input_payload = payload.get("input", {})
    alignment = input_payload.get(
        "alignment", input_payload.get("embedding_alignment", {})
    )

    return {
        "embedding_model": model,
        "embedding_label": MODEL_LABELS.get(model, model),
        "source": source,
        "comparison_set": comparison_set,
        "variant": variant,
        "feature": feature,
        "reducer": reducer,
        "dimension": input_payload.get("embedding_dimension"),
        "classifier": experiment.get("classifier"),
        "train_target": train_target,
        "evaluation_target": evaluation_target,
        "mean_validation_accuracy": _mean(
            metric.get("accuracy") for metric in validation_metrics
        ),
        "std_validation_accuracy": _std(
            metric.get("accuracy") for metric in validation_metrics
        ),
        "mean_validation_auc": _mean(
            metric.get("auc") for metric in validation_metrics
        ),
        "std_validation_auc": _std(
            metric.get("auc") for metric in validation_metrics
        ),
        "mean_test_accuracy": _mean(row.get("accuracy") for row in results),
        "mean_test_auc": _mean(row.get("auc") for row in results),
        "mean_test_balanced_accuracy": _mean(
            row.get("balanced_accuracy") for row in results
        ),
        "mean_test_accuracy_lift_vs_majority": _mean(
            row.get("accuracy_lift_vs_majority") for row in results
        ),
        "test_years": test_years,
        "folds": len(results),
        "panel_rows": alignment.get("panel_rows"),
        "matched_rows": alignment.get("matched_rows"),
        "alignment_key_mode": alignment.get(
            "key_mode", alignment.get("method")
        ),
        "report": str(report_path.resolve()),
    }


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _candidate_rows(
    cninfo_results: Path,
    dense_results: Path,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    primary: list[dict[str, Any]] = []
    legacy: list[dict[str, Any]] = []

    for path in sorted(cninfo_results.glob("*.json")):
        if path.name.endswith(".summary.json"):
            continue
        payload = _load(path)
        experiment = payload.get("experiment", {})
        design = payload.get("design", {})
        train_target, evaluation_target = _targets(design)
        if (
            train_target != "event_return_3d"
            or evaluation_target != "next_day_return"
            or experiment.get("classifier") != "logistic"
            or experiment.get("variant") != "plain"
            or experiment.get("feature") != "full_mean"
        ):
            continue
        if experiment.get("model") not in PRIMARY_CNINFO_MODELS:
            continue
        if experiment.get("reducer") != "none":
            continue
        primary.append(
            summarize_report_payload(
                payload,
                path,
                source="cninfo_method_pooled",
                comparison_set="primary",
            )
        )

    for path in sorted(dense_results.glob("*.json")):
        if path.name.endswith(".summary.json"):
            continue
        payload = _load(path)
        experiment = payload.get("experiment", {})
        design = payload.get("design", {})
        train_target, evaluation_target = _targets(design)
        if (
            train_target != "event_return_3d"
            or evaluation_target != "next_day_return"
            or experiment.get("classifier") != "logistic"
            or experiment.get("input_name") != "sina_single_stock_text"
        ):
            continue
        model = experiment.get("embedding_model")
        if experiment.get("reducer") != "none":
            continue
        comparison_set = "primary" if model in PRIMARY_DENSE_MODELS else "legacy"
        destination = primary if comparison_set == "primary" else legacy
        destination.append(
            summarize_report_payload(
                payload,
                path,
                source="single_stock_precomputed",
                comparison_set=comparison_set,
            )
        )

    return primary, legacy


def _deduplicate(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str, str, str], list[dict[str, Any]]] = {}
    for row in rows:
        key = (
            str(row["comparison_set"]),
            str(row["embedding_model"]),
            str(row["variant"]),
            str(row["feature"]),
        )
        grouped.setdefault(key, []).append(row)
    duplicates = {key: values for key, values in grouped.items() if len(values) != 1}
    if duplicates:
        details = "; ".join(
            f"{key}: {len(values)} reports" for key, values in duplicates.items()
        )
        raise ValueError(f"expected one report per comparison cell; found {details}")
    return [values[0] for values in grouped.values()]


def _rank(rows: list[dict[str, Any]], metric: str) -> None:
    ordered = sorted(
        rows,
        key=lambda row: (
            row[metric] is not None,
            row[metric] if row[metric] is not None else float("-inf"),
        ),
        reverse=True,
    )
    for rank, row in enumerate(ordered, start=1):
        row[f"rank_{metric}"] = rank


def _audit(rows: list[dict[str, Any]], expected_panel_rows: int) -> list[str]:
    errors: list[str] = []
    for row in rows:
        if row["train_target"] != "event_return_3d":
            errors.append(f"{row['embedding_model']}: unexpected train target")
        if row["evaluation_target"] != "next_day_return":
            errors.append(f"{row['embedding_model']}: unexpected evaluation target")
        if row["classifier"] != "logistic":
            errors.append(f"{row['embedding_model']}: unexpected classifier")
        if row["variant"] != "plain" or row["feature"] not in {"full_mean", "global_mean"}:
            errors.append(f"{row['embedding_model']}: not a plain pooled feature")
        if row["test_years"] != list(EXPECTED_TEST_YEARS):
            errors.append(
                f"{row['embedding_model']}: test years {row['test_years']}"
            )
        if row["folds"] != len(EXPECTED_TEST_YEARS):
            errors.append(f"{row['embedding_model']}: expected four test folds")
        if row["panel_rows"] != expected_panel_rows:
            errors.append(
                f"{row['embedding_model']}: panel rows {row['panel_rows']}"
            )
        if row["matched_rows"] != expected_panel_rows:
            errors.append(
                f"{row['embedding_model']}: matched rows {row['matched_rows']}"
            )
    return errors


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    fields = [key for key in rows[0] if key != "test_years"] + ["test_years"]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            output = dict(row)
            output["test_years"] = ",".join(map(str, row["test_years"]))
            writer.writerow(output)


def build_comparison(
    *,
    cninfo_results: Path,
    dense_results: Path,
    expected_panel_rows: int,
) -> dict[str, Any]:
    primary, legacy = _candidate_rows(cninfo_results, dense_results)
    primary = _deduplicate(primary)
    legacy = _deduplicate(legacy) if legacy else []
    expected_count = len(PRIMARY_CNINFO_MODELS) + len(PRIMARY_DENSE_MODELS)
    if len(primary) != expected_count:
        observed = sorted(row["embedding_model"] for row in primary)
        raise ValueError(f"primary comparison is incomplete: {observed}")
    _rank(primary, "mean_validation_accuracy")
    _rank(primary, "mean_validation_auc")
    _rank(primary, "mean_test_accuracy")
    _rank(primary, "mean_test_auc")
    errors = _audit(primary, expected_panel_rows)
    if errors:
        raise ValueError("comparison audit failed: " + "; ".join(errors))

    by_validation_accuracy = min(
        primary, key=lambda row: row["rank_mean_validation_accuracy"]
    )
    by_validation_auc = min(primary, key=lambda row: row["rank_mean_validation_auc"])
    by_test_accuracy = min(primary, key=lambda row: row["rank_mean_test_accuracy"])
    by_test_auc = min(primary, key=lambda row: row["rank_mean_test_auc"])
    return {
        "protocol": {
            "panel_rows": expected_panel_rows,
            "fit_years": 6,
            "validation_years": 2,
            "test_years": 1,
            "test_folds": list(EXPECTED_TEST_YEARS),
            "train_target": "event_return_3d",
            "evaluation_target": "next_day_return",
            "classifier": "logistic",
            "primary_feature": "plain pooled full_mean",
            "selection_rule": (
                "select on mean validation metric; test metrics are diagnostic only"
            ),
        },
        "primary": primary,
        "legacy_separate": legacy,
        "selection": {
            "validation_accuracy": {
                "embedding_model": by_validation_accuracy["embedding_model"],
                "embedding_label": by_validation_accuracy["embedding_label"],
                "value": by_validation_accuracy["mean_validation_accuracy"],
            },
            "validation_auc": {
                "embedding_model": by_validation_auc["embedding_model"],
                "embedding_label": by_validation_auc["embedding_label"],
                "value": by_validation_auc["mean_validation_auc"],
            },
        },
        "diagnostic_oos": {
            "test_accuracy": {
                "embedding_model": by_test_accuracy["embedding_model"],
                "embedding_label": by_test_accuracy["embedding_label"],
                "value": by_test_accuracy["mean_test_accuracy"],
            },
            "test_auc": {
                "embedding_model": by_test_auc["embedding_model"],
                "embedding_label": by_test_auc["embedding_label"],
                "value": by_test_auc["mean_test_auc"],
            },
        },
        "excluded_from_primary": {
            "unmatched_or_incomplete_reports": (
                "reports with another panel, prompt condition, reducer, classifier, "
                "or fewer than four test folds"
            ),
            "tfidf_bow_lexicon": (
                "traditional text baselines do not have a matching four-fold result "
                "on this 4,928-row panel in the selected report directories"
            ),
            "prompt_token_features": (
                "representation ablation; keep separate from pooled full_mean"
            ),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cninfo-results",
        type=Path,
        default=Path(
            "/home/gaozh/news_content_quality_20260812/"
            "cninfo_method_v1/classification"
        ),
    )
    parser.add_argument(
        "--dense-results",
        type=Path,
        default=Path(
            "/home/gaozh/news_content_quality_20260812/classification/results"
        ),
    )
    parser.add_argument("--expected-panel-rows", type=int, default=4928)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(
            "reports/classification/sina_embedding_comparison/comparison.json"
        ),
    )
    args = parser.parse_args()
    comparison = build_comparison(
        cninfo_results=args.cninfo_results,
        dense_results=args.dense_results,
        expected_panel_rows=args.expected_panel_rows,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(comparison, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    _write_csv(args.output.with_suffix(".csv"), comparison["primary"])
    _write_csv(
        args.output.with_name("legacy_separate.csv"), comparison["legacy_separate"]
    )
    print(json.dumps(comparison["selection"], ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()